# Generated by Django 3.2.4 on 2021-10-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_orderitem_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
