# Generated by Django 3.2.4 on 2021-10-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20211017_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='collection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
