# Generated by Django 3.2.4 on 2021-10-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20211023_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='screen',
            new_name='nav_bar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='screen',
            new_name='new',
        ),
        migrations.AddField(
            model_name='category',
            name='adds',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='adds',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0),
        ),
    ]
