# Generated by Django 3.2.4 on 2021-10-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20211027_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='foot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
