# Generated by Django 3.2.4 on 2021-10-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_category_foot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='adds',
        ),
        migrations.AddField(
            model_name='product',
            name='add',
            field=models.FloatField(default=0),
        ),
    ]
