# Generated by Django 3.2.4 on 2021-10-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_auto_20211027_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
