# Generated by Django 3.2.4 on 2021-11-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20211101_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
