# Generated by Django 3.2.4 on 2022-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20211110_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='require',
            name='file',
            field=models.FileField(blank=True, upload_to='require/'),
        ),
        migrations.AddField(
            model_name='require',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
